// /api/og-share.js
// Dynamic branded Open Graph image for /s/<slug> unfurls.
//
// Canvas height ADAPTS to the preview aspect so nothing gets cropped and
// there's no empty space:
//   - Horizontal preview (16:9) → canvas ~1200x785
//   - Square preview  (1:1)    → canvas  1200x1310
//   - Vertical preview (2:3)   → canvas  1200x1910
// The preview fills the top; the pre-baked /public/og-brand-strip.png
// (1200x110 band with aiPRINT.ai + "Shared with you") sits flush below.
//
// The brand strip is a static asset (generated by
// scripts/build-og-brand-strip.mjs) so no fonts need to resolve in the
// Vercel serverless runtime — sharp just composites rasters.
//
// Wired up via /api/s.js which emits
// `<meta property="og:image" content="/api/og-share?slug=<slug>">`.

import sharp from 'sharp';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { getSharedDesign } from './db/index.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BRAND_STRIP_PATH = path.resolve(__dirname, '../public/og-brand-strip.png');

const SLUG_RE = /^[a-zA-Z0-9]{6,16}$/;
const CANVAS_WIDTH = 1200;
const STRIP_HEIGHT = 110; // must match scripts/build-og-brand-strip.mjs
// Guard rails so a weird preview can't blow up the canvas. Covers everything
// from ultra-wide panoramas to tall portraits without crawlers barfing.
const MIN_PREVIEW_H = 400;
const MAX_PREVIEW_H = 1800;
const BG = '#0a0f1d';

// Read the brand-strip once at cold start. Bundled into the function via
// vercel.json → functions["api/og-share.js"].includeFiles.
let brandStripBuf = null;
function loadBrandStrip() {
  if (!brandStripBuf) {
    try {
      brandStripBuf = fs.readFileSync(BRAND_STRIP_PATH);
    } catch (err) {
      console.error('og-share: missing brand strip asset:', err?.message);
    }
  }
  return brandStripBuf;
}

async function fetchBuffer(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`fetch ${url} -> ${r.status}`);
  return Buffer.from(await r.arrayBuffer());
}

// Shared size-calc so /api/s.js can mirror it when emitting og:image:width/height.
// Exported so s.js can pull the same numbers instead of reimplementing them.
export function computeCanvasSize(prevW, prevH) {
  let previewH = 630;
  if (prevW && prevH) {
    previewH = Math.round(CANVAS_WIDTH * (prevH / prevW));
    previewH = Math.max(MIN_PREVIEW_H, Math.min(MAX_PREVIEW_H, previewH));
  }
  return {
    previewH,
    width: CANVAS_WIDTH,
    height: previewH + STRIP_HEIGHT
  };
}

export default async function handler(req, res) {
  const proto = (req.headers['x-forwarded-proto'] || 'https').split(',')[0].trim();
  const host = req.headers.host || 'aiprint.ai';
  const origin = `${proto}://${host}`;

  try {
    const slug = (req.query && (req.query.slug || req.query.s)) || '';
    if (!slug || !SLUG_RE.test(slug)) {
      res.writeHead(302, { Location: '/og-image.png' });
      return res.end();
    }

    const row = await getSharedDesign(slug).catch(() => null);
    const payload = row?.payload;
    const previewUrl = payload?.preview?.url;
    if (!previewUrl) {
      res.writeHead(302, { Location: '/og-image.png' });
      return res.end();
    }

    // Prefer stored width/height (set at save time). If missing, read from the
    // image itself as a fallback.
    let prevW = payload?.preview?.width || null;
    let prevH = payload?.preview?.height || null;

    const previewBuf = await fetchBuffer(previewUrl);
    if (!prevW || !prevH) {
      const meta = await sharp(previewBuf).metadata();
      prevW = meta.width;
      prevH = meta.height;
    }

    const { previewH, width: W, height: H } = computeCanvasSize(prevW, prevH);

    // Resize preview to exact aspect (fill to width=1200 & previewH, using
    // cover in case rounding creates a 1px mismatch).
    const resizedPreview = await sharp(previewBuf)
      .resize(W, previewH, { fit: 'cover', position: 'center' })
      .toBuffer();

    const composites = [{ input: resizedPreview, top: 0, left: 0 }];
    const strip = loadBrandStrip();
    if (strip) composites.push({ input: strip, top: previewH, left: 0 });

    const composited = await sharp({
      create: {
        width: W,
        height: H,
        channels: 4,
        background: BG
      }
    })
      .composite(composites)
      .png({ compressionLevel: 8 })
      .toBuffer();

    res.setHeader('Content-Type', 'image/png');
    res.setHeader('Cache-Control', 'public, max-age=3600, s-maxage=604800, stale-while-revalidate=2592000');
    return res.status(200).send(composited);
  } catch (err) {
    console.error('og-share error:', err?.message);
    res.writeHead(302, { Location: `${origin}/og-image.png` });
    return res.end();
  }
}
