// /api/og-share.js
// Dynamic branded Open Graph image for /s/<slug> unfurls. Takes the shared
// preview, cover-fits it onto a 1200x630 OG canvas, and composites the
// pre-rendered /public/og-brand-strip.png overlay across the bottom (logo
// + aiPRINT.ai wordmark + "Shared with you — canvas · metal · acrylic").
// So iMessage/SMS/Slack unfurls look like a gallery card instead of a raw
// image dump.
//
// The brand strip is a static asset (generated by
// scripts/build-og-brand-strip.mjs) so no fonts need to resolve in the
// Vercel serverless runtime — sharp just composites two rasters.
//
// Wired up via /api/s.js which emits
// `<meta property="og:image" content="/api/og-share?slug=<slug>">`.

import sharp from 'sharp';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { getSharedDesign } from './db/index.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BRAND_STRIP_PATH = path.resolve(__dirname, '../public/og-brand-strip.png');

const SLUG_RE = /^[a-zA-Z0-9]{6,16}$/;
const WIDTH = 1200;
const HEIGHT = 630;

// Read the brand-strip once at cold start. Included in the deployment via
// a Vercel functions include (see vercel.json).
let brandStripBuf = null;
function loadBrandStrip() {
  if (!brandStripBuf) {
    try {
      brandStripBuf = fs.readFileSync(BRAND_STRIP_PATH);
    } catch (err) {
      console.error('og-share: missing brand strip asset:', err?.message);
    }
  }
  return brandStripBuf;
}

async function fetchBuffer(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`fetch ${url} -> ${r.status}`);
  return Buffer.from(await r.arrayBuffer());
}

export default async function handler(req, res) {
  const proto = (req.headers['x-forwarded-proto'] || 'https').split(',')[0].trim();
  const host = req.headers.host || 'aiprint.ai';
  const origin = `${proto}://${host}`;

  try {
    const slug = (req.query && (req.query.slug || req.query.s)) || '';
    if (!slug || !SLUG_RE.test(slug)) {
      res.writeHead(302, { Location: '/og-image.png' });
      return res.end();
    }

    const row = await getSharedDesign(slug).catch(() => null);
    const previewUrl = row?.payload?.preview?.url;
    if (!previewUrl) {
      // No preview on file — fall back to the static site OG so the unfurl
      // still looks branded rather than broken.
      res.writeHead(302, { Location: '/og-image.png' });
      return res.end();
    }

    // Cover-fit the preview onto the OG canvas.
    const previewBuf = await fetchBuffer(previewUrl);
    const coverBuf = await sharp(previewBuf)
      .resize(WIDTH, HEIGHT, { fit: 'cover', position: 'attention' })
      .toBuffer();

    const composites = [];
    const strip = loadBrandStrip();
    if (strip) composites.push({ input: strip, top: 0, left: 0 });

    const composited = await sharp(coverBuf)
      .composite(composites)
      .png({ compressionLevel: 8 })
      .toBuffer();

    res.setHeader('Content-Type', 'image/png');
    // Immutable per-share — cache hard at the edge so repeated crawls are free.
    res.setHeader('Cache-Control', 'public, max-age=3600, s-maxage=604800, stale-while-revalidate=2592000');
    return res.status(200).send(composited);
  } catch (err) {
    console.error('og-share error:', err?.message);
    // On any failure, redirect to the static OG so the unfurl doesn't break.
    res.writeHead(302, { Location: `${origin}/og-image.png` });
    return res.end();
  }
}
